#!/bin/bash

# Clear case
rm -rf D2Q9_lattice
rm -rf processor*
rm -rf *.pvd

# Compute lattice
latticeMesh -d D2Q9 --semiPeriodicBox

# lattice partitioning
latticeMeshPartition -n 2 -d D2Q9

# field partitioning
latticeFieldsPartition -n 2 -d D2Q9
