#!/bin/bash

# Compute lattice
latticeMesh -d D2Q9 --semiPeriodicBox

# # lattice partitioning
# latticeMeshPartition -n $1 -d D2Q9

# # field partitioning
# latticeFieldsPartition -n $1 -d D2Q9

# # initial equilibrium distributions
# mpiexec -n $1 twoPhasesFields
